# Generated by Django 4.2.15 on 2024-09-01 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_timestamp_payment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='matric_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student_gmail',
        ),
        migrations.AddField(
            model_name='payment',
            name='gmail',
            field=models.EmailField(default='John@gm.dm', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='matric',
            field=models.CharField(default='qwerty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='receiver',
            field=models.CharField(default='werty', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='sender',
            field=models.CharField(default='345tyhgvc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='payment.department')),
            ],
        ),
    ]
