# Generated by Django 4.2.15 on 2024-09-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_department_remove_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_ngn',
            field=models.IntegerField(default=20000, verbose_name='AMOUNT (NGN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=18, verbose_name='AMOUNT (ETH)'),
        ),
    ]
